/******************************************************************************
*  Generated by PSoC Designer 5.4.2946
******************************************************************************/
#include <m8c.h>
// LCD_1D4 address and mask defines
#pragma	ioport	LCD_1D4_Data_ADDR:	0x0
BYTE			LCD_1D4_Data_ADDR;
#pragma	ioport	LCD_1D4_DriveMode_0_ADDR:	0x100
BYTE			LCD_1D4_DriveMode_0_ADDR;
#pragma	ioport	LCD_1D4_DriveMode_1_ADDR:	0x101
BYTE			LCD_1D4_DriveMode_1_ADDR;
#pragma	ioport	LCD_1D4_DriveMode_2_ADDR:	0x3
BYTE			LCD_1D4_DriveMode_2_ADDR;
#pragma	ioport	LCD_1D4_GlobalSelect_ADDR:	0x2
BYTE			LCD_1D4_GlobalSelect_ADDR;
#pragma	ioport	LCD_1D4_IntCtrl_0_ADDR:	0x102
BYTE			LCD_1D4_IntCtrl_0_ADDR;
#pragma	ioport	LCD_1D4_IntCtrl_1_ADDR:	0x103
BYTE			LCD_1D4_IntCtrl_1_ADDR;
#pragma	ioport	LCD_1D4_IntEn_ADDR:	0x1
BYTE			LCD_1D4_IntEn_ADDR;
#define LCD_1D4_MASK 0x1
// LCD_1D4 Shadow defines
//   LCD_1D4_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define LCD_1D4_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
//   LCD_1D4_DriveMode_0Shadow define
extern BYTE Port_0_DriveMode_0_SHADE;
#define LCD_1D4_DriveMode_0Shadow (*(unsigned char*)&Port_0_DriveMode_0_SHADE)
//   LCD_1D4_DriveMode_1Shadow define
extern BYTE Port_0_DriveMode_1_SHADE;
#define LCD_1D4_DriveMode_1Shadow (*(unsigned char*)&Port_0_DriveMode_1_SHADE)
// LCD_1D5 address and mask defines
#pragma	ioport	LCD_1D5_Data_ADDR:	0x0
BYTE			LCD_1D5_Data_ADDR;
#pragma	ioport	LCD_1D5_DriveMode_0_ADDR:	0x100
BYTE			LCD_1D5_DriveMode_0_ADDR;
#pragma	ioport	LCD_1D5_DriveMode_1_ADDR:	0x101
BYTE			LCD_1D5_DriveMode_1_ADDR;
#pragma	ioport	LCD_1D5_DriveMode_2_ADDR:	0x3
BYTE			LCD_1D5_DriveMode_2_ADDR;
#pragma	ioport	LCD_1D5_GlobalSelect_ADDR:	0x2
BYTE			LCD_1D5_GlobalSelect_ADDR;
#pragma	ioport	LCD_1D5_IntCtrl_0_ADDR:	0x102
BYTE			LCD_1D5_IntCtrl_0_ADDR;
#pragma	ioport	LCD_1D5_IntCtrl_1_ADDR:	0x103
BYTE			LCD_1D5_IntCtrl_1_ADDR;
#pragma	ioport	LCD_1D5_IntEn_ADDR:	0x1
BYTE			LCD_1D5_IntEn_ADDR;
#define LCD_1D5_MASK 0x2
// LCD_1D5 Shadow defines
//   LCD_1D5_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define LCD_1D5_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
//   LCD_1D5_DriveMode_0Shadow define
extern BYTE Port_0_DriveMode_0_SHADE;
#define LCD_1D5_DriveMode_0Shadow (*(unsigned char*)&Port_0_DriveMode_0_SHADE)
//   LCD_1D5_DriveMode_1Shadow define
extern BYTE Port_0_DriveMode_1_SHADE;
#define LCD_1D5_DriveMode_1Shadow (*(unsigned char*)&Port_0_DriveMode_1_SHADE)
// LCD_1D6 address and mask defines
#pragma	ioport	LCD_1D6_Data_ADDR:	0x0
BYTE			LCD_1D6_Data_ADDR;
#pragma	ioport	LCD_1D6_DriveMode_0_ADDR:	0x100
BYTE			LCD_1D6_DriveMode_0_ADDR;
#pragma	ioport	LCD_1D6_DriveMode_1_ADDR:	0x101
BYTE			LCD_1D6_DriveMode_1_ADDR;
#pragma	ioport	LCD_1D6_DriveMode_2_ADDR:	0x3
BYTE			LCD_1D6_DriveMode_2_ADDR;
#pragma	ioport	LCD_1D6_GlobalSelect_ADDR:	0x2
BYTE			LCD_1D6_GlobalSelect_ADDR;
#pragma	ioport	LCD_1D6_IntCtrl_0_ADDR:	0x102
BYTE			LCD_1D6_IntCtrl_0_ADDR;
#pragma	ioport	LCD_1D6_IntCtrl_1_ADDR:	0x103
BYTE			LCD_1D6_IntCtrl_1_ADDR;
#pragma	ioport	LCD_1D6_IntEn_ADDR:	0x1
BYTE			LCD_1D6_IntEn_ADDR;
#define LCD_1D6_MASK 0x4
// LCD_1D6 Shadow defines
//   LCD_1D6_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define LCD_1D6_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
//   LCD_1D6_DriveMode_0Shadow define
extern BYTE Port_0_DriveMode_0_SHADE;
#define LCD_1D6_DriveMode_0Shadow (*(unsigned char*)&Port_0_DriveMode_0_SHADE)
//   LCD_1D6_DriveMode_1Shadow define
extern BYTE Port_0_DriveMode_1_SHADE;
#define LCD_1D6_DriveMode_1Shadow (*(unsigned char*)&Port_0_DriveMode_1_SHADE)
// LCD_1D7 address and mask defines
#pragma	ioport	LCD_1D7_Data_ADDR:	0x0
BYTE			LCD_1D7_Data_ADDR;
#pragma	ioport	LCD_1D7_DriveMode_0_ADDR:	0x100
BYTE			LCD_1D7_DriveMode_0_ADDR;
#pragma	ioport	LCD_1D7_DriveMode_1_ADDR:	0x101
BYTE			LCD_1D7_DriveMode_1_ADDR;
#pragma	ioport	LCD_1D7_DriveMode_2_ADDR:	0x3
BYTE			LCD_1D7_DriveMode_2_ADDR;
#pragma	ioport	LCD_1D7_GlobalSelect_ADDR:	0x2
BYTE			LCD_1D7_GlobalSelect_ADDR;
#pragma	ioport	LCD_1D7_IntCtrl_0_ADDR:	0x102
BYTE			LCD_1D7_IntCtrl_0_ADDR;
#pragma	ioport	LCD_1D7_IntCtrl_1_ADDR:	0x103
BYTE			LCD_1D7_IntCtrl_1_ADDR;
#pragma	ioport	LCD_1D7_IntEn_ADDR:	0x1
BYTE			LCD_1D7_IntEn_ADDR;
#define LCD_1D7_MASK 0x8
// LCD_1D7 Shadow defines
//   LCD_1D7_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define LCD_1D7_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
//   LCD_1D7_DriveMode_0Shadow define
extern BYTE Port_0_DriveMode_0_SHADE;
#define LCD_1D7_DriveMode_0Shadow (*(unsigned char*)&Port_0_DriveMode_0_SHADE)
//   LCD_1D7_DriveMode_1Shadow define
extern BYTE Port_0_DriveMode_1_SHADE;
#define LCD_1D7_DriveMode_1Shadow (*(unsigned char*)&Port_0_DriveMode_1_SHADE)
// LCD_1E address and mask defines
#pragma	ioport	LCD_1E_Data_ADDR:	0x0
BYTE			LCD_1E_Data_ADDR;
#pragma	ioport	LCD_1E_DriveMode_0_ADDR:	0x100
BYTE			LCD_1E_DriveMode_0_ADDR;
#pragma	ioport	LCD_1E_DriveMode_1_ADDR:	0x101
BYTE			LCD_1E_DriveMode_1_ADDR;
#pragma	ioport	LCD_1E_DriveMode_2_ADDR:	0x3
BYTE			LCD_1E_DriveMode_2_ADDR;
#pragma	ioport	LCD_1E_GlobalSelect_ADDR:	0x2
BYTE			LCD_1E_GlobalSelect_ADDR;
#pragma	ioport	LCD_1E_IntCtrl_0_ADDR:	0x102
BYTE			LCD_1E_IntCtrl_0_ADDR;
#pragma	ioport	LCD_1E_IntCtrl_1_ADDR:	0x103
BYTE			LCD_1E_IntCtrl_1_ADDR;
#pragma	ioport	LCD_1E_IntEn_ADDR:	0x1
BYTE			LCD_1E_IntEn_ADDR;
#define LCD_1E_MASK 0x10
// LCD_1E Shadow defines
//   LCD_1E_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define LCD_1E_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
//   LCD_1E_DriveMode_0Shadow define
extern BYTE Port_0_DriveMode_0_SHADE;
#define LCD_1E_DriveMode_0Shadow (*(unsigned char*)&Port_0_DriveMode_0_SHADE)
//   LCD_1E_DriveMode_1Shadow define
extern BYTE Port_0_DriveMode_1_SHADE;
#define LCD_1E_DriveMode_1Shadow (*(unsigned char*)&Port_0_DriveMode_1_SHADE)
// LCD_1RS address and mask defines
#pragma	ioport	LCD_1RS_Data_ADDR:	0x0
BYTE			LCD_1RS_Data_ADDR;
#pragma	ioport	LCD_1RS_DriveMode_0_ADDR:	0x100
BYTE			LCD_1RS_DriveMode_0_ADDR;
#pragma	ioport	LCD_1RS_DriveMode_1_ADDR:	0x101
BYTE			LCD_1RS_DriveMode_1_ADDR;
#pragma	ioport	LCD_1RS_DriveMode_2_ADDR:	0x3
BYTE			LCD_1RS_DriveMode_2_ADDR;
#pragma	ioport	LCD_1RS_GlobalSelect_ADDR:	0x2
BYTE			LCD_1RS_GlobalSelect_ADDR;
#pragma	ioport	LCD_1RS_IntCtrl_0_ADDR:	0x102
BYTE			LCD_1RS_IntCtrl_0_ADDR;
#pragma	ioport	LCD_1RS_IntCtrl_1_ADDR:	0x103
BYTE			LCD_1RS_IntCtrl_1_ADDR;
#pragma	ioport	LCD_1RS_IntEn_ADDR:	0x1
BYTE			LCD_1RS_IntEn_ADDR;
#define LCD_1RS_MASK 0x20
// LCD_1RS Shadow defines
//   LCD_1RS_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define LCD_1RS_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
//   LCD_1RS_DriveMode_0Shadow define
extern BYTE Port_0_DriveMode_0_SHADE;
#define LCD_1RS_DriveMode_0Shadow (*(unsigned char*)&Port_0_DriveMode_0_SHADE)
//   LCD_1RS_DriveMode_1Shadow define
extern BYTE Port_0_DriveMode_1_SHADE;
#define LCD_1RS_DriveMode_1Shadow (*(unsigned char*)&Port_0_DriveMode_1_SHADE)
// LCD_1RW address and mask defines
#pragma	ioport	LCD_1RW_Data_ADDR:	0x0
BYTE			LCD_1RW_Data_ADDR;
#pragma	ioport	LCD_1RW_DriveMode_0_ADDR:	0x100
BYTE			LCD_1RW_DriveMode_0_ADDR;
#pragma	ioport	LCD_1RW_DriveMode_1_ADDR:	0x101
BYTE			LCD_1RW_DriveMode_1_ADDR;
#pragma	ioport	LCD_1RW_DriveMode_2_ADDR:	0x3
BYTE			LCD_1RW_DriveMode_2_ADDR;
#pragma	ioport	LCD_1RW_GlobalSelect_ADDR:	0x2
BYTE			LCD_1RW_GlobalSelect_ADDR;
#pragma	ioport	LCD_1RW_IntCtrl_0_ADDR:	0x102
BYTE			LCD_1RW_IntCtrl_0_ADDR;
#pragma	ioport	LCD_1RW_IntCtrl_1_ADDR:	0x103
BYTE			LCD_1RW_IntCtrl_1_ADDR;
#pragma	ioport	LCD_1RW_IntEn_ADDR:	0x1
BYTE			LCD_1RW_IntEn_ADDR;
#define LCD_1RW_MASK 0x40
// LCD_1RW Shadow defines
//   LCD_1RW_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define LCD_1RW_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
//   LCD_1RW_DriveMode_0Shadow define
extern BYTE Port_0_DriveMode_0_SHADE;
#define LCD_1RW_DriveMode_0Shadow (*(unsigned char*)&Port_0_DriveMode_0_SHADE)
//   LCD_1RW_DriveMode_1Shadow define
extern BYTE Port_0_DriveMode_1_SHADE;
#define LCD_1RW_DriveMode_1Shadow (*(unsigned char*)&Port_0_DriveMode_1_SHADE)
// Xtal_Out address and mask defines
#pragma	ioport	Xtal_Out_Data_ADDR:	0x4
BYTE			Xtal_Out_Data_ADDR;
#pragma	ioport	Xtal_Out_DriveMode_0_ADDR:	0x104
BYTE			Xtal_Out_DriveMode_0_ADDR;
#pragma	ioport	Xtal_Out_DriveMode_1_ADDR:	0x105
BYTE			Xtal_Out_DriveMode_1_ADDR;
#pragma	ioport	Xtal_Out_DriveMode_2_ADDR:	0x7
BYTE			Xtal_Out_DriveMode_2_ADDR;
#pragma	ioport	Xtal_Out_GlobalSelect_ADDR:	0x6
BYTE			Xtal_Out_GlobalSelect_ADDR;
#pragma	ioport	Xtal_Out_IntCtrl_0_ADDR:	0x106
BYTE			Xtal_Out_IntCtrl_0_ADDR;
#pragma	ioport	Xtal_Out_IntCtrl_1_ADDR:	0x107
BYTE			Xtal_Out_IntCtrl_1_ADDR;
#pragma	ioport	Xtal_Out_IntEn_ADDR:	0x5
BYTE			Xtal_Out_IntEn_ADDR;
#define Xtal_Out_MASK 0x1
// Xtal_In address and mask defines
#pragma	ioport	Xtal_In_Data_ADDR:	0x4
BYTE			Xtal_In_Data_ADDR;
#pragma	ioport	Xtal_In_DriveMode_0_ADDR:	0x104
BYTE			Xtal_In_DriveMode_0_ADDR;
#pragma	ioport	Xtal_In_DriveMode_1_ADDR:	0x105
BYTE			Xtal_In_DriveMode_1_ADDR;
#pragma	ioport	Xtal_In_DriveMode_2_ADDR:	0x7
BYTE			Xtal_In_DriveMode_2_ADDR;
#pragma	ioport	Xtal_In_GlobalSelect_ADDR:	0x6
BYTE			Xtal_In_GlobalSelect_ADDR;
#pragma	ioport	Xtal_In_IntCtrl_0_ADDR:	0x106
BYTE			Xtal_In_IntCtrl_0_ADDR;
#pragma	ioport	Xtal_In_IntCtrl_1_ADDR:	0x107
BYTE			Xtal_In_IntCtrl_1_ADDR;
#pragma	ioport	Xtal_In_IntEn_ADDR:	0x5
BYTE			Xtal_In_IntEn_ADDR;
#define Xtal_In_MASK 0x2
// MISO address and mask defines
#pragma	ioport	MISO_Data_ADDR:	0x8
BYTE			MISO_Data_ADDR;
#pragma	ioport	MISO_DriveMode_0_ADDR:	0x108
BYTE			MISO_DriveMode_0_ADDR;
#pragma	ioport	MISO_DriveMode_1_ADDR:	0x109
BYTE			MISO_DriveMode_1_ADDR;
#pragma	ioport	MISO_DriveMode_2_ADDR:	0xb
BYTE			MISO_DriveMode_2_ADDR;
#pragma	ioport	MISO_GlobalSelect_ADDR:	0xa
BYTE			MISO_GlobalSelect_ADDR;
#pragma	ioport	MISO_IntCtrl_0_ADDR:	0x10a
BYTE			MISO_IntCtrl_0_ADDR;
#pragma	ioport	MISO_IntCtrl_1_ADDR:	0x10b
BYTE			MISO_IntCtrl_1_ADDR;
#pragma	ioport	MISO_IntEn_ADDR:	0x9
BYTE			MISO_IntEn_ADDR;
#define MISO_MASK 0x1
// MISO Shadow defines
//   MISO_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define MISO_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// MOSI address and mask defines
#pragma	ioport	MOSI_Data_ADDR:	0x8
BYTE			MOSI_Data_ADDR;
#pragma	ioport	MOSI_DriveMode_0_ADDR:	0x108
BYTE			MOSI_DriveMode_0_ADDR;
#pragma	ioport	MOSI_DriveMode_1_ADDR:	0x109
BYTE			MOSI_DriveMode_1_ADDR;
#pragma	ioport	MOSI_DriveMode_2_ADDR:	0xb
BYTE			MOSI_DriveMode_2_ADDR;
#pragma	ioport	MOSI_GlobalSelect_ADDR:	0xa
BYTE			MOSI_GlobalSelect_ADDR;
#pragma	ioport	MOSI_IntCtrl_0_ADDR:	0x10a
BYTE			MOSI_IntCtrl_0_ADDR;
#pragma	ioport	MOSI_IntCtrl_1_ADDR:	0x10b
BYTE			MOSI_IntCtrl_1_ADDR;
#pragma	ioport	MOSI_IntEn_ADDR:	0x9
BYTE			MOSI_IntEn_ADDR;
#define MOSI_MASK 0x2
// MOSI Shadow defines
//   MOSI_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define MOSI_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// CLK address and mask defines
#pragma	ioport	CLK_Data_ADDR:	0x8
BYTE			CLK_Data_ADDR;
#pragma	ioport	CLK_DriveMode_0_ADDR:	0x108
BYTE			CLK_DriveMode_0_ADDR;
#pragma	ioport	CLK_DriveMode_1_ADDR:	0x109
BYTE			CLK_DriveMode_1_ADDR;
#pragma	ioport	CLK_DriveMode_2_ADDR:	0xb
BYTE			CLK_DriveMode_2_ADDR;
#pragma	ioport	CLK_GlobalSelect_ADDR:	0xa
BYTE			CLK_GlobalSelect_ADDR;
#pragma	ioport	CLK_IntCtrl_0_ADDR:	0x10a
BYTE			CLK_IntCtrl_0_ADDR;
#pragma	ioport	CLK_IntCtrl_1_ADDR:	0x10b
BYTE			CLK_IntCtrl_1_ADDR;
#pragma	ioport	CLK_IntEn_ADDR:	0x9
BYTE			CLK_IntEn_ADDR;
#define CLK_MASK 0x4
// CLK Shadow defines
//   CLK_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define CLK_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// CSPin address and mask defines
#pragma	ioport	CSPin_Data_ADDR:	0x8
BYTE			CSPin_Data_ADDR;
#pragma	ioport	CSPin_DriveMode_0_ADDR:	0x108
BYTE			CSPin_DriveMode_0_ADDR;
#pragma	ioport	CSPin_DriveMode_1_ADDR:	0x109
BYTE			CSPin_DriveMode_1_ADDR;
#pragma	ioport	CSPin_DriveMode_2_ADDR:	0xb
BYTE			CSPin_DriveMode_2_ADDR;
#pragma	ioport	CSPin_GlobalSelect_ADDR:	0xa
BYTE			CSPin_GlobalSelect_ADDR;
#pragma	ioport	CSPin_IntCtrl_0_ADDR:	0x10a
BYTE			CSPin_IntCtrl_0_ADDR;
#pragma	ioport	CSPin_IntCtrl_1_ADDR:	0x10b
BYTE			CSPin_IntCtrl_1_ADDR;
#pragma	ioport	CSPin_IntEn_ADDR:	0x9
BYTE			CSPin_IntEn_ADDR;
#define CSPin_MASK 0x8
// CSPin Shadow defines
//   CSPin_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define CSPin_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// AGND address and mask defines
#pragma	ioport	AGND_Data_ADDR:	0x8
BYTE			AGND_Data_ADDR;
#pragma	ioport	AGND_DriveMode_0_ADDR:	0x108
BYTE			AGND_DriveMode_0_ADDR;
#pragma	ioport	AGND_DriveMode_1_ADDR:	0x109
BYTE			AGND_DriveMode_1_ADDR;
#pragma	ioport	AGND_DriveMode_2_ADDR:	0xb
BYTE			AGND_DriveMode_2_ADDR;
#pragma	ioport	AGND_GlobalSelect_ADDR:	0xa
BYTE			AGND_GlobalSelect_ADDR;
#pragma	ioport	AGND_IntCtrl_0_ADDR:	0x10a
BYTE			AGND_IntCtrl_0_ADDR;
#pragma	ioport	AGND_IntCtrl_1_ADDR:	0x10b
BYTE			AGND_IntCtrl_1_ADDR;
#pragma	ioport	AGND_IntEn_ADDR:	0x9
BYTE			AGND_IntEn_ADDR;
#define AGND_MASK 0x10
// AGND Shadow defines
//   AGND_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define AGND_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
