/******************************************************************************
*  Generated by PSoC Designer 5.4.2946
******************************************************************************/
#include <m8c.h>
// LCD_1D4 address and mask defines
#pragma	ioport	LCD_1D4_Data_ADDR:	0x0
BYTE			LCD_1D4_Data_ADDR;
#pragma	ioport	LCD_1D4_DriveMode_0_ADDR:	0x100
BYTE			LCD_1D4_DriveMode_0_ADDR;
#pragma	ioport	LCD_1D4_DriveMode_1_ADDR:	0x101
BYTE			LCD_1D4_DriveMode_1_ADDR;
#pragma	ioport	LCD_1D4_DriveMode_2_ADDR:	0x3
BYTE			LCD_1D4_DriveMode_2_ADDR;
#pragma	ioport	LCD_1D4_GlobalSelect_ADDR:	0x2
BYTE			LCD_1D4_GlobalSelect_ADDR;
#pragma	ioport	LCD_1D4_IntCtrl_0_ADDR:	0x102
BYTE			LCD_1D4_IntCtrl_0_ADDR;
#pragma	ioport	LCD_1D4_IntCtrl_1_ADDR:	0x103
BYTE			LCD_1D4_IntCtrl_1_ADDR;
#pragma	ioport	LCD_1D4_IntEn_ADDR:	0x1
BYTE			LCD_1D4_IntEn_ADDR;
#define LCD_1D4_MASK 0x1
// LCD_1D4 Shadow defines
//   LCD_1D4_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define LCD_1D4_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
//   LCD_1D4_DriveMode_0Shadow define
extern BYTE Port_0_DriveMode_0_SHADE;
#define LCD_1D4_DriveMode_0Shadow (*(unsigned char*)&Port_0_DriveMode_0_SHADE)
//   LCD_1D4_DriveMode_1Shadow define
extern BYTE Port_0_DriveMode_1_SHADE;
#define LCD_1D4_DriveMode_1Shadow (*(unsigned char*)&Port_0_DriveMode_1_SHADE)
// LCD_1D5 address and mask defines
#pragma	ioport	LCD_1D5_Data_ADDR:	0x0
BYTE			LCD_1D5_Data_ADDR;
#pragma	ioport	LCD_1D5_DriveMode_0_ADDR:	0x100
BYTE			LCD_1D5_DriveMode_0_ADDR;
#pragma	ioport	LCD_1D5_DriveMode_1_ADDR:	0x101
BYTE			LCD_1D5_DriveMode_1_ADDR;
#pragma	ioport	LCD_1D5_DriveMode_2_ADDR:	0x3
BYTE			LCD_1D5_DriveMode_2_ADDR;
#pragma	ioport	LCD_1D5_GlobalSelect_ADDR:	0x2
BYTE			LCD_1D5_GlobalSelect_ADDR;
#pragma	ioport	LCD_1D5_IntCtrl_0_ADDR:	0x102
BYTE			LCD_1D5_IntCtrl_0_ADDR;
#pragma	ioport	LCD_1D5_IntCtrl_1_ADDR:	0x103
BYTE			LCD_1D5_IntCtrl_1_ADDR;
#pragma	ioport	LCD_1D5_IntEn_ADDR:	0x1
BYTE			LCD_1D5_IntEn_ADDR;
#define LCD_1D5_MASK 0x2
// LCD_1D5 Shadow defines
//   LCD_1D5_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define LCD_1D5_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
//   LCD_1D5_DriveMode_0Shadow define
extern BYTE Port_0_DriveMode_0_SHADE;
#define LCD_1D5_DriveMode_0Shadow (*(unsigned char*)&Port_0_DriveMode_0_SHADE)
//   LCD_1D5_DriveMode_1Shadow define
extern BYTE Port_0_DriveMode_1_SHADE;
#define LCD_1D5_DriveMode_1Shadow (*(unsigned char*)&Port_0_DriveMode_1_SHADE)
// LCD_1D6 address and mask defines
#pragma	ioport	LCD_1D6_Data_ADDR:	0x0
BYTE			LCD_1D6_Data_ADDR;
#pragma	ioport	LCD_1D6_DriveMode_0_ADDR:	0x100
BYTE			LCD_1D6_DriveMode_0_ADDR;
#pragma	ioport	LCD_1D6_DriveMode_1_ADDR:	0x101
BYTE			LCD_1D6_DriveMode_1_ADDR;
#pragma	ioport	LCD_1D6_DriveMode_2_ADDR:	0x3
BYTE			LCD_1D6_DriveMode_2_ADDR;
#pragma	ioport	LCD_1D6_GlobalSelect_ADDR:	0x2
BYTE			LCD_1D6_GlobalSelect_ADDR;
#pragma	ioport	LCD_1D6_IntCtrl_0_ADDR:	0x102
BYTE			LCD_1D6_IntCtrl_0_ADDR;
#pragma	ioport	LCD_1D6_IntCtrl_1_ADDR:	0x103
BYTE			LCD_1D6_IntCtrl_1_ADDR;
#pragma	ioport	LCD_1D6_IntEn_ADDR:	0x1
BYTE			LCD_1D6_IntEn_ADDR;
#define LCD_1D6_MASK 0x4
// LCD_1D6 Shadow defines
//   LCD_1D6_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define LCD_1D6_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
//   LCD_1D6_DriveMode_0Shadow define
extern BYTE Port_0_DriveMode_0_SHADE;
#define LCD_1D6_DriveMode_0Shadow (*(unsigned char*)&Port_0_DriveMode_0_SHADE)
//   LCD_1D6_DriveMode_1Shadow define
extern BYTE Port_0_DriveMode_1_SHADE;
#define LCD_1D6_DriveMode_1Shadow (*(unsigned char*)&Port_0_DriveMode_1_SHADE)
// LCD_1D7 address and mask defines
#pragma	ioport	LCD_1D7_Data_ADDR:	0x0
BYTE			LCD_1D7_Data_ADDR;
#pragma	ioport	LCD_1D7_DriveMode_0_ADDR:	0x100
BYTE			LCD_1D7_DriveMode_0_ADDR;
#pragma	ioport	LCD_1D7_DriveMode_1_ADDR:	0x101
BYTE			LCD_1D7_DriveMode_1_ADDR;
#pragma	ioport	LCD_1D7_DriveMode_2_ADDR:	0x3
BYTE			LCD_1D7_DriveMode_2_ADDR;
#pragma	ioport	LCD_1D7_GlobalSelect_ADDR:	0x2
BYTE			LCD_1D7_GlobalSelect_ADDR;
#pragma	ioport	LCD_1D7_IntCtrl_0_ADDR:	0x102
BYTE			LCD_1D7_IntCtrl_0_ADDR;
#pragma	ioport	LCD_1D7_IntCtrl_1_ADDR:	0x103
BYTE			LCD_1D7_IntCtrl_1_ADDR;
#pragma	ioport	LCD_1D7_IntEn_ADDR:	0x1
BYTE			LCD_1D7_IntEn_ADDR;
#define LCD_1D7_MASK 0x8
// LCD_1D7 Shadow defines
//   LCD_1D7_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define LCD_1D7_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
//   LCD_1D7_DriveMode_0Shadow define
extern BYTE Port_0_DriveMode_0_SHADE;
#define LCD_1D7_DriveMode_0Shadow (*(unsigned char*)&Port_0_DriveMode_0_SHADE)
//   LCD_1D7_DriveMode_1Shadow define
extern BYTE Port_0_DriveMode_1_SHADE;
#define LCD_1D7_DriveMode_1Shadow (*(unsigned char*)&Port_0_DriveMode_1_SHADE)
// LCD_1E address and mask defines
#pragma	ioport	LCD_1E_Data_ADDR:	0x0
BYTE			LCD_1E_Data_ADDR;
#pragma	ioport	LCD_1E_DriveMode_0_ADDR:	0x100
BYTE			LCD_1E_DriveMode_0_ADDR;
#pragma	ioport	LCD_1E_DriveMode_1_ADDR:	0x101
BYTE			LCD_1E_DriveMode_1_ADDR;
#pragma	ioport	LCD_1E_DriveMode_2_ADDR:	0x3
BYTE			LCD_1E_DriveMode_2_ADDR;
#pragma	ioport	LCD_1E_GlobalSelect_ADDR:	0x2
BYTE			LCD_1E_GlobalSelect_ADDR;
#pragma	ioport	LCD_1E_IntCtrl_0_ADDR:	0x102
BYTE			LCD_1E_IntCtrl_0_ADDR;
#pragma	ioport	LCD_1E_IntCtrl_1_ADDR:	0x103
BYTE			LCD_1E_IntCtrl_1_ADDR;
#pragma	ioport	LCD_1E_IntEn_ADDR:	0x1
BYTE			LCD_1E_IntEn_ADDR;
#define LCD_1E_MASK 0x10
// LCD_1E Shadow defines
//   LCD_1E_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define LCD_1E_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
//   LCD_1E_DriveMode_0Shadow define
extern BYTE Port_0_DriveMode_0_SHADE;
#define LCD_1E_DriveMode_0Shadow (*(unsigned char*)&Port_0_DriveMode_0_SHADE)
//   LCD_1E_DriveMode_1Shadow define
extern BYTE Port_0_DriveMode_1_SHADE;
#define LCD_1E_DriveMode_1Shadow (*(unsigned char*)&Port_0_DriveMode_1_SHADE)
// LCD_1RS address and mask defines
#pragma	ioport	LCD_1RS_Data_ADDR:	0x0
BYTE			LCD_1RS_Data_ADDR;
#pragma	ioport	LCD_1RS_DriveMode_0_ADDR:	0x100
BYTE			LCD_1RS_DriveMode_0_ADDR;
#pragma	ioport	LCD_1RS_DriveMode_1_ADDR:	0x101
BYTE			LCD_1RS_DriveMode_1_ADDR;
#pragma	ioport	LCD_1RS_DriveMode_2_ADDR:	0x3
BYTE			LCD_1RS_DriveMode_2_ADDR;
#pragma	ioport	LCD_1RS_GlobalSelect_ADDR:	0x2
BYTE			LCD_1RS_GlobalSelect_ADDR;
#pragma	ioport	LCD_1RS_IntCtrl_0_ADDR:	0x102
BYTE			LCD_1RS_IntCtrl_0_ADDR;
#pragma	ioport	LCD_1RS_IntCtrl_1_ADDR:	0x103
BYTE			LCD_1RS_IntCtrl_1_ADDR;
#pragma	ioport	LCD_1RS_IntEn_ADDR:	0x1
BYTE			LCD_1RS_IntEn_ADDR;
#define LCD_1RS_MASK 0x20
// LCD_1RS Shadow defines
//   LCD_1RS_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define LCD_1RS_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
//   LCD_1RS_DriveMode_0Shadow define
extern BYTE Port_0_DriveMode_0_SHADE;
#define LCD_1RS_DriveMode_0Shadow (*(unsigned char*)&Port_0_DriveMode_0_SHADE)
//   LCD_1RS_DriveMode_1Shadow define
extern BYTE Port_0_DriveMode_1_SHADE;
#define LCD_1RS_DriveMode_1Shadow (*(unsigned char*)&Port_0_DriveMode_1_SHADE)
// LCD_1RW address and mask defines
#pragma	ioport	LCD_1RW_Data_ADDR:	0x0
BYTE			LCD_1RW_Data_ADDR;
#pragma	ioport	LCD_1RW_DriveMode_0_ADDR:	0x100
BYTE			LCD_1RW_DriveMode_0_ADDR;
#pragma	ioport	LCD_1RW_DriveMode_1_ADDR:	0x101
BYTE			LCD_1RW_DriveMode_1_ADDR;
#pragma	ioport	LCD_1RW_DriveMode_2_ADDR:	0x3
BYTE			LCD_1RW_DriveMode_2_ADDR;
#pragma	ioport	LCD_1RW_GlobalSelect_ADDR:	0x2
BYTE			LCD_1RW_GlobalSelect_ADDR;
#pragma	ioport	LCD_1RW_IntCtrl_0_ADDR:	0x102
BYTE			LCD_1RW_IntCtrl_0_ADDR;
#pragma	ioport	LCD_1RW_IntCtrl_1_ADDR:	0x103
BYTE			LCD_1RW_IntCtrl_1_ADDR;
#pragma	ioport	LCD_1RW_IntEn_ADDR:	0x1
BYTE			LCD_1RW_IntEn_ADDR;
#define LCD_1RW_MASK 0x40
// LCD_1RW Shadow defines
//   LCD_1RW_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define LCD_1RW_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
//   LCD_1RW_DriveMode_0Shadow define
extern BYTE Port_0_DriveMode_0_SHADE;
#define LCD_1RW_DriveMode_0Shadow (*(unsigned char*)&Port_0_DriveMode_0_SHADE)
//   LCD_1RW_DriveMode_1Shadow define
extern BYTE Port_0_DriveMode_1_SHADE;
#define LCD_1RW_DriveMode_1Shadow (*(unsigned char*)&Port_0_DriveMode_1_SHADE)
// XTAL_Out address and mask defines
#pragma	ioport	XTAL_Out_Data_ADDR:	0x4
BYTE			XTAL_Out_Data_ADDR;
#pragma	ioport	XTAL_Out_DriveMode_0_ADDR:	0x104
BYTE			XTAL_Out_DriveMode_0_ADDR;
#pragma	ioport	XTAL_Out_DriveMode_1_ADDR:	0x105
BYTE			XTAL_Out_DriveMode_1_ADDR;
#pragma	ioport	XTAL_Out_DriveMode_2_ADDR:	0x7
BYTE			XTAL_Out_DriveMode_2_ADDR;
#pragma	ioport	XTAL_Out_GlobalSelect_ADDR:	0x6
BYTE			XTAL_Out_GlobalSelect_ADDR;
#pragma	ioport	XTAL_Out_IntCtrl_0_ADDR:	0x106
BYTE			XTAL_Out_IntCtrl_0_ADDR;
#pragma	ioport	XTAL_Out_IntCtrl_1_ADDR:	0x107
BYTE			XTAL_Out_IntCtrl_1_ADDR;
#pragma	ioport	XTAL_Out_IntEn_ADDR:	0x5
BYTE			XTAL_Out_IntEn_ADDR;
#define XTAL_Out_MASK 0x1
// XTAL_Out Shadow defines
//   XTAL_Out_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define XTAL_Out_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// XTAL_In address and mask defines
#pragma	ioport	XTAL_In_Data_ADDR:	0x4
BYTE			XTAL_In_Data_ADDR;
#pragma	ioport	XTAL_In_DriveMode_0_ADDR:	0x104
BYTE			XTAL_In_DriveMode_0_ADDR;
#pragma	ioport	XTAL_In_DriveMode_1_ADDR:	0x105
BYTE			XTAL_In_DriveMode_1_ADDR;
#pragma	ioport	XTAL_In_DriveMode_2_ADDR:	0x7
BYTE			XTAL_In_DriveMode_2_ADDR;
#pragma	ioport	XTAL_In_GlobalSelect_ADDR:	0x6
BYTE			XTAL_In_GlobalSelect_ADDR;
#pragma	ioport	XTAL_In_IntCtrl_0_ADDR:	0x106
BYTE			XTAL_In_IntCtrl_0_ADDR;
#pragma	ioport	XTAL_In_IntCtrl_1_ADDR:	0x107
BYTE			XTAL_In_IntCtrl_1_ADDR;
#pragma	ioport	XTAL_In_IntEn_ADDR:	0x5
BYTE			XTAL_In_IntEn_ADDR;
#define XTAL_In_MASK 0x2
// XTAL_In Shadow defines
//   XTAL_In_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define XTAL_In_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// TXD address and mask defines
#pragma	ioport	TXD_Data_ADDR:	0x4
BYTE			TXD_Data_ADDR;
#pragma	ioport	TXD_DriveMode_0_ADDR:	0x104
BYTE			TXD_DriveMode_0_ADDR;
#pragma	ioport	TXD_DriveMode_1_ADDR:	0x105
BYTE			TXD_DriveMode_1_ADDR;
#pragma	ioport	TXD_DriveMode_2_ADDR:	0x7
BYTE			TXD_DriveMode_2_ADDR;
#pragma	ioport	TXD_GlobalSelect_ADDR:	0x6
BYTE			TXD_GlobalSelect_ADDR;
#pragma	ioport	TXD_IntCtrl_0_ADDR:	0x106
BYTE			TXD_IntCtrl_0_ADDR;
#pragma	ioport	TXD_IntCtrl_1_ADDR:	0x107
BYTE			TXD_IntCtrl_1_ADDR;
#pragma	ioport	TXD_IntEn_ADDR:	0x5
BYTE			TXD_IntEn_ADDR;
#define TXD_MASK 0x8
// TXD Shadow defines
//   TXD_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define TXD_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// SIPin address and mask defines
#pragma	ioport	SIPin_Data_ADDR:	0x4
BYTE			SIPin_Data_ADDR;
#pragma	ioport	SIPin_DriveMode_0_ADDR:	0x104
BYTE			SIPin_DriveMode_0_ADDR;
#pragma	ioport	SIPin_DriveMode_1_ADDR:	0x105
BYTE			SIPin_DriveMode_1_ADDR;
#pragma	ioport	SIPin_DriveMode_2_ADDR:	0x7
BYTE			SIPin_DriveMode_2_ADDR;
#pragma	ioport	SIPin_GlobalSelect_ADDR:	0x6
BYTE			SIPin_GlobalSelect_ADDR;
#pragma	ioport	SIPin_IntCtrl_0_ADDR:	0x106
BYTE			SIPin_IntCtrl_0_ADDR;
#pragma	ioport	SIPin_IntCtrl_1_ADDR:	0x107
BYTE			SIPin_IntCtrl_1_ADDR;
#pragma	ioport	SIPin_IntEn_ADDR:	0x5
BYTE			SIPin_IntEn_ADDR;
#define SIPin_MASK 0x20
// SIPin Shadow defines
//   SIPin_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define SIPin_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// CLKPin address and mask defines
#pragma	ioport	CLKPin_Data_ADDR:	0x4
BYTE			CLKPin_Data_ADDR;
#pragma	ioport	CLKPin_DriveMode_0_ADDR:	0x104
BYTE			CLKPin_DriveMode_0_ADDR;
#pragma	ioport	CLKPin_DriveMode_1_ADDR:	0x105
BYTE			CLKPin_DriveMode_1_ADDR;
#pragma	ioport	CLKPin_DriveMode_2_ADDR:	0x7
BYTE			CLKPin_DriveMode_2_ADDR;
#pragma	ioport	CLKPin_GlobalSelect_ADDR:	0x6
BYTE			CLKPin_GlobalSelect_ADDR;
#pragma	ioport	CLKPin_IntCtrl_0_ADDR:	0x106
BYTE			CLKPin_IntCtrl_0_ADDR;
#pragma	ioport	CLKPin_IntCtrl_1_ADDR:	0x107
BYTE			CLKPin_IntCtrl_1_ADDR;
#pragma	ioport	CLKPin_IntEn_ADDR:	0x5
BYTE			CLKPin_IntEn_ADDR;
#define CLKPin_MASK 0x80
// CLKPin Shadow defines
//   CLKPin_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define CLKPin_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// AGND address and mask defines
#pragma	ioport	AGND_Data_ADDR:	0x8
BYTE			AGND_Data_ADDR;
#pragma	ioport	AGND_DriveMode_0_ADDR:	0x108
BYTE			AGND_DriveMode_0_ADDR;
#pragma	ioport	AGND_DriveMode_1_ADDR:	0x109
BYTE			AGND_DriveMode_1_ADDR;
#pragma	ioport	AGND_DriveMode_2_ADDR:	0xb
BYTE			AGND_DriveMode_2_ADDR;
#pragma	ioport	AGND_GlobalSelect_ADDR:	0xa
BYTE			AGND_GlobalSelect_ADDR;
#pragma	ioport	AGND_IntCtrl_0_ADDR:	0x10a
BYTE			AGND_IntCtrl_0_ADDR;
#pragma	ioport	AGND_IntCtrl_1_ADDR:	0x10b
BYTE			AGND_IntCtrl_1_ADDR;
#pragma	ioport	AGND_IntEn_ADDR:	0x9
BYTE			AGND_IntEn_ADDR;
#define AGND_MASK 0x10
