//*****************************************************************************
//*****************************************************************************
//  FILENAME:  SAR6_1.h
//  Version: 1.5, Updated on 2013/5/19 at 10:44:11
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION:  SAR6 User Module C Language interface file.
//
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef SAR6_1_INCLUDE
#define SAR6_1_INCLUDE

#include "m8c.h"

//-------------------------------------------------
// Defines for SAR6_1 API's.
//-------------------------------------------------
#define SAR6_1_OFF         0
#define SAR6_1_LOWPOWER    1
#define SAR6_1_MEDPOWER    2
#define SAR6_1_HIGHPOWER   3
#define SAR6_1_FULLPOWER   3

//-------------------------------------------------
// Prototypes of the SAR6_1 API.
//-------------------------------------------------
#pragma fastcall16 SAR6_1_Start
#pragma fastcall16 SAR6_1_SetPower
#pragma fastcall16 SAR6_1_cGetSample
#pragma fastcall16 SAR6_1_Stop

extern void SAR6_1_Start( BYTE bPowerSetting );
extern void SAR6_1_SetPower( BYTE bPowerSetting );
extern CHAR SAR6_1_cGetSample( void );
extern void SAR6_1_Stop( void );

//--------------------------------------------------
// WARNING!  This function prototype will be removed
//           in a future version.
//--------------------------------------------------
#pragma fastcall16 SAR6_1_GetSample
extern CHAR SAR6_1_GetSample( void );

//-------------------------------------------------
// Register Addresses for SAR6_1
//-------------------------------------------------
#pragma ioport  SAR6_1_CR0: 0x080
BYTE            SAR6_1_CR0;
#pragma ioport  SAR6_1_CR1: 0x081
BYTE            SAR6_1_CR1;
#pragma ioport  SAR6_1_CR2: 0x082
BYTE            SAR6_1_CR2;
#pragma ioport  SAR6_1_CR3: 0x083
BYTE            SAR6_1_CR3;

#endif
// end of file SAR6_1.h
