//*****************************************************************************
//*****************************************************************************
//  FILENAME: DigInv_1.h
//   Version: 1.60, Updated on 2013/5/19 at 10:43:26
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION:
//    DigInv_1 DigInverter User Module header file.
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef DigInv_1_INCLUDE
#define DigInv_1_INCLUDE

#include <m8c.h>

/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  DigInv_1_EnableInt
#pragma fastcall16  DigInv_1_DisableInt
#pragma fastcall16  DigInv_1_Start
#pragma fastcall16  DigInv_1_Stop

//-------------------------------------------------
// Prototypes of the DigInv_1 API.
//-------------------------------------------------
extern void  DigInv_1_EnableInt(void);           // Proxy Class 1
extern void  DigInv_1_DisableInt(void);          // Proxy Class 1
extern void  DigInv_1_Start(void);               // Proxy Class 1
extern void  DigInv_1_Stop(void);                // Proxy Class 1

//-------------------------------------------------
// Hardware Register Definitions
//-------------------------------------------------
#pragma ioport  DigInv_1_CONTROL_REG:   0x023
BYTE            DigInv_1_CONTROL_REG;                      //Control register
#pragma ioport  DigInv_1_COUNTER_REG:   0x020
BYTE            DigInv_1_COUNTER_REG;                      //Counter register
#pragma ioport  DigInv_1_PERIOD_REG:    0x021
BYTE            DigInv_1_PERIOD_REG;                       //Period value register
#pragma ioport  DigInv_1_COMPARE_REG:   0x022
BYTE            DigInv_1_COMPARE_REG;                      //CompareValue register
#pragma ioport  DigInv_1_FUNC_REG:  0x120
BYTE            DigInv_1_FUNC_REG;                         //Function register
#pragma ioport  DigInv_1_INPUT_REG: 0x121
BYTE            DigInv_1_INPUT_REG;                        //Input register
#pragma ioport  DigInv_1_OUTPUT_REG:    0x122
BYTE            DigInv_1_OUTPUT_REG;                       //Output register

#endif
// end of file DigInv_1.h
